package ubis;

import java.util.Collections;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.control.Label;
import javafx.scene.layout.HBox;

/**
 * A UI component representing a dialog box consisting of a message label.
 */
public class DialogBox extends HBox {
    private Label text;

    /**
     * Constructs a DialogBox with the specified message text.
     *
     * @param message Text content of the dialog.
     */
    public DialogBox(String message) {
        text = new Label(message);
        text.setWrapText(true);

        this.setPadding(new Insets(6, 10, 6, 10));
        this.setSpacing(10);
        this.getChildren().add(text);
    }

    /**
     * Flips the dialog box orientation such that the message appears on the left side.
     */
    private void flip() {
        ObservableList<Node> tmp = FXCollections.observableArrayList(this.getChildren());
        Collections.reverse(tmp);
        getChildren().setAll(tmp);
        setAlignment(Pos.TOP_LEFT);
    }

    /**
     * Creates and returns a DialogBox configured for user messages.
     *
     * @param text Message text sent by the user.
     * @return DialogBox styled for user messages.
     */
    public static DialogBox getUserDialog(String text) {
        DialogBox db = new DialogBox(text);
        db.setAlignment(Pos.TOP_RIGHT);
        db.text.setStyle("-fx-background-color: #DCF8C6; -fx-padding: 8px 12px; "
                + "-fx-background-radius: 12px; -fx-font-size: 13px;");
        return db;
    }

    /**
     * Creates and returns a DialogBox configured for chatbot responses.
     *
     * @param text Message text generated by Ubis.
     * @return DialogBox styled for Ubis responses.
     */
    public static DialogBox getUbisDialog(String text) {
        DialogBox db = new DialogBox(text);
        db.flip();
        db.text.setStyle("-fx-background-color: #EFEFEF; -fx-padding: 8px 12px; "
                + "-fx-background-radius: 12px; -fx-font-size: 13px;");
        return db;
    }
}
